baseURL = 'https://yourusername.github.io/tarik-portfolio/'
languageCode = 'en-us'
title = 'OBS Productions Blog'
theme = 'PaperMod'

[params]
  env = "production"
  description = "OBS Productions - Creative Video & Film Production Blog"
  keywords = ["video production", "film", "creative", "commercial", "corporate videos"]
  author = "OBS Productions"
  DateFormat = "January 2, 2006"
  defaultTheme = "auto"
  disableThemeToggle = false
  ShowReadingTime = true
  ShowShareButtons = true
  ShowPostNavLinks = true
  ShowBreadCrumbs = true
  ShowCodeCopyButtons = true
  ShowWordCount = true
  ShowRssButtonInSectionTermList = true
  UseHugoToc = true
  disableSpecial1stPost = false
  disableScrollToTop = false
  comments = false
  hidemeta = false
  hideSummary = false
  showtoc = false
  tocopen = false

  [params.assets]
    favicon = "/favicon.ico"
    favicon16x16 = "/favicon-16x16.png"
    favicon32x32 = "/favicon-32x32.png"
    apple_touch_icon = "/apple-touch-icon.png"
    safari_pinned_tab = "/safari-pinned-tab.svg"

  [params.label]
    text = "OBS Productions Blog"
    icon = "/apple-touch-icon.png"
    iconHeight = 35

  [params.profileMode]
    enabled = false

  [params.homeInfoParams]
    Title = "Welcome to OBS Productions Blog"
    Content = "Creative insights, behind-the-scenes content, and industry news from our video production team."

  [[params.socialIcons]]
    name = "youtube"
    url = "https://youtube.com"

  [[params.socialIcons]]
    name = "instagram"
    url = "https://instagram.com"

  [[params.socialIcons]]
    name = "linkedin"
    url = "https://linkedin.com"

[menu]
  [[menu.main]]
    identifier = "home"
    name = "Home"
    url = "/"
    weight = 10

  [[menu.main]]
    identifier = "posts"
    name = "Posts"
    url = "/posts/"
    weight = 20

  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 30

  [[menu.main]]
    identifier = "contact"
    name = "Contact"
    url = "/contact/"
    weight = 40

[markup]
  [markup.highlight]
    noClasses = false
    codeFences = true
    guessSyntax = true
    lineNos = true
    style = "github"

[outputs]
  home = ["HTML", "RSS", "JSON"]