baseURL = 'https://yourusername.github.io/tarik-booking/'
languageCode = 'en-us'
title = 'OBS Productions Gallery'
theme = 'gallery'

[params]
  description = "OBS Productions - Creative Video & Film Production Portfolio"
  keywords = ["video production", "film", "creative", "commercial", "corporate videos", "portfolio", "gallery"]
  
  # Author configuration for RSS feed
  [params.author]
    name = "OBS Productions"
    email = "info@obsproductions.com"
  
  # Gallery theme specific settings
  title = "OBS Productions"
  subtitle = "Creative Video & Film Production"
  footer = "&copy; 2025 OBS Productions. All rights reserved."
  
  # Main website link
  main_site = "../frontend/index.html"
  
  # Social links
  [[params.social]]
    name = "YouTube"
    url = "https://youtube.com"
    icon = "youtube"
  
  [[params.social]]
    name = "Instagram" 
    url = "https://instagram.com"
    icon = "instagram"
    
  [[params.social]]
    name = "LinkedIn"
    url = "https://linkedin.com"
    icon = "linkedin"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
    
  [[menu.main]]
    name = "About"
    url = "/about/"
    weight = 20
    
  [[menu.main]]
    name = "Contact"
    url = "/contact/"
    weight = 30
    
  [[menu.main]]
    name = "Main Site"
    url = "../frontend/index.html"
    weight = 40

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

# Disable RSS if not needed (optional)
[outputs]
  home = ["HTML"]
  section = ["HTML"]